import { MessageType } from "./types";
export declare const WILDCARD = "*";
export declare const HAND_SHAKE = "__FRAME_MESSAGE_HANDLE_SHAKE__";
export declare const isInternalType: (type: MessageType) => boolean;
export declare const isNative: (fn: Function) => boolean;
export declare const noop: () => void;
export declare const warn: (...log: any[]) => void;
export declare const generateUid: () => string;
export declare const delay: (timeout: number) => Promise<void>;
export declare const filter: <T>(arr: T[], match: (item: T) => boolean) => T[];
